import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function showHelp() {
  console.log(`
CyberGuard Test Scaffold Generator
----------------------------------
Usage:
  node scripts/generate-test.js <target-js-file> <global-module-name> [dependency-js-files...]

Example:
  node scripts/generate-test.js public/js/cyber-notify.js CyberNotify
  node scripts/generate-test.js public/js/project-manager.js ProjectManager public/js/api-client.js
`);
}

function generate(targetFile, globalModuleName, dependencies) {
  const absoluteTarget = path.resolve(targetFile);
  if (!fs.existsSync(absoluteTarget)) {
    console.error(`Error: Target file not found at ${targetFile}`);
    process.exit(1);
  }

  const baseName = path.basename(targetFile, '.js');
  const testFileName = `${baseName}.test.js`;
  const testsDir = path.resolve(__dirname, '../tests/unit');
  
  if (!fs.existsSync(testsDir)) {
    fs.mkdirSync(testsDir, { recursive: true });
  }

  const testFilePath = path.join(testsDir, testFileName);
  
  if (fs.existsSync(testFilePath)) {
    console.error(`Error: Test file already exists at ${path.relative(process.cwd(), testFilePath)}`);
    process.exit(1);
  }

  // Calculate relative paths for file loading
  const relativeTargetFromTest = path.relative(testsDir, absoluteTarget).replace(/\\/g, '/');
  
  const dependencyLoads = dependencies.map(dep => {
    const absDep = path.resolve(dep);
    if (!fs.existsSync(absDep)) {
      console.warn(`Warning: Dependency file not found at ${dep}`);
    }
    const relDep = path.relative(testsDir, absDep).replace(/\\/g, '/');
    const depVarName = path.basename(dep, '.js').replace(/[^a-zA-Z0-9]/g, '') + 'Code';
    return {
      variable: depVarName,
      path: relDep,
      read: `const ${depVarName} = fs.readFileSync(path.resolve(__dirname, '${relDep}'), 'utf8');`,
      eval: `window.eval(${depVarName});`
    };
  });

  const targetVarName = baseName.replace(/[^a-zA-Z0-9]/g, '') + 'Code';

  const testTemplate = `/**
 * Unit Tests for ${globalModuleName} Module
 * Automatically generated by test scaffold generator.
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { JSDOM } from 'jsdom';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

describe('${globalModuleName} Module', () => {
  let dom;
  let window;
  let document;

  beforeEach(() => {
    // Setup fresh isolated JSDOM environment
    dom = new JSDOM(\`
      <!DOCTYPE html>
      <html>
        <body>
          <!-- Add DOM structure needed for tests here -->
          <div id="app-container"></div>
        </body>
      </html>
    \`, {
      url: "http://localhost",
      runScripts: "dangerously",
      resources: "usable"
    });
    window = dom.window;
    document = window.document;

    // Set globals for test execution context
    global.window = window;
    global.document = document;
    global.localStorage = window.localStorage;
    global.CustomEvent = window.CustomEvent;

    // Mock global UI/loading indicators
    window.showLoading = vi.fn();
    window.hideLoading = vi.fn();
    window.showContainerLoading = vi.fn();
    window.hideContainerLoading = vi.fn();
    global.showLoading = window.showLoading;
    global.hideLoading = window.hideLoading;

    // Mock CyberNotify toast notifications
    window.CyberNotify = {
      alert: vi.fn(),
      confirm: vi.fn((msg, callback) => callback(true))
    };
    global.CyberNotify = window.CyberNotify;

    // Read source codes
    ${dependencyLoads.map(d => d.read).join('\n    ')}
    const ${targetVarName} = fs.readFileSync(path.resolve(__dirname, '${relativeTargetFromTest}'), 'utf8');

    // Eval dependencies first in JSDOM context
    ${dependencyLoads.map(d => d.eval).join('\n    ')}

    // Eval target module code
    window.eval(${targetVarName});
  });

  afterEach(() => {
    // Tear down globals to prevent test bleed
    delete global.window;
    delete global.document;
    delete global.localStorage;
    delete global.CustomEvent;
    delete global.showLoading;
    delete global.hideLoading;
    delete global.CyberNotify;
    vi.clearAllMocks();
  });

  it('should initialize successfully in JSDOM context', () => {
    // Verify module existence
    expect(window.${globalModuleName}).toBeDefined();
    
    // Example: verify init method or initial properties
    if (typeof window.${globalModuleName}.init === 'function') {
      window.${globalModuleName}.init();
    }
  });

  it('should handle basic functionality correctly', () => {
    // Add logic tests here
  });
});
`;

  fs.writeFileSync(testFilePath, testTemplate, 'utf8');
  const relCreatedPath = path.relative(process.cwd(), testFilePath).replace(/\\/g, '/');
  console.log(`\n[SUCCESS] Test scaffold generated at ${relCreatedPath}`);
  console.log(`>>> Run this test file using:`);
  console.log(`    npx vitest run ${relCreatedPath}\n`);
}

const args = process.argv.slice(2);
if (args.length < 2) {
  showHelp();
  process.exit(1);
}

const [targetFile, globalModuleName, ...dependencies] = args;
generate(targetFile, globalModuleName, dependencies);
